### ISSUE TITLE
Numbers - Larger - Take a look when you can

### ISSUE THREAD

**Issue by sravenscraft** [sravenscraft/b3-fw-ug#139]
So, the numbers have really been irking me, they felt weak on the canvases. This is where LUC.EDU is. I adjusted them on desktop and sm breakpoint. Ted is hesitant to go to light, we need a solution using the compressed let me know how this feels to you. For me it feels like the panel now holds it's weight with or against the others. Also, I believe a user takes each panel in one at a time (especially on a laptop, phone even more so) - they disengage with the previous panel once they engage with the next but the numbers had no landing spot, now they do. We might still need to pump more white space in the canvases all around. Will discuss on Monday.

**Comment by johndrevs** [comment]
where should I look at it?

**Comment by sravenscraft** [comment]
IMPORTANT: If this broke numbers anywhere no worries. Don't try to fix it. It's just there to consider. It's easy to revert Monday.

**Comment by sravenscraft** [comment]
You'll see it on the canvases when the master is pulled.

**Comment by johndrevs** [comment]
I like the larger numbers. make a greater statement. especially where they are being relied on to hold more water in the thinner canvases.

**Comment by sravenscraft** [comment]
OK. Let's roll with that. Have you seen an issue with the Study Abroad canvas?

Stephen Ravenscraft
Web Designer
Office: 312-915-6367
Cell: 630-750-1986
Studio: 630-916-3234

On Jul 30, 2017, at 8:36 AM, John Drevs <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the larger numbers. make a greater statement. especially where they are being relied on to hold more water in the thinner canvases.

-

**Comment by johndrevs** [comment]
Theres a merge conflict in the code. Is that what youre talking about?
I can fix that. The number content doesn't have the new better larger style,

**Comment by saradiemer** [comment]
The numbers look great--thanks, Steve. I only see it breaking on the Chicago and Sustainability canvas (4 numbers instead of 3). I'll take a look at the 4 across pattern.
