### ISSUE TITLE
Update Canvases

### ISSUE THREAD

**Issue by sravenscraft** [sravenscraft/b3-fw-ug#66]
**Canvas Panel Updates - 071017**

• Add "display-large" class to all h5 panel headlines
• Check to make sure all "cta" hrefs have the "cta" class
• Update all blockquotes to @fotoole version on the cost canvas
• Add "panel-dark" class to numbers panels

**Comment by sravenscraft** [comment]
I think this is complete, let me know and I'll close it.

**Comment by johndrevs** [comment]
The issue as presented can be closed but Im not sure where canvases are. Im sure pretty close.

**Comment by sravenscraft** [comment]
Stephen Ravenscraft
Web Designer
Office: 312-915-6367
Cell: 630-750-1986
Studio: 630-916-3234

On Jul 29, 2017, at 5:31 PM, John Drevs <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue as presented can be closed but Im not sure where canvases are. Im sure pretty close.

-

**Comment by saradiemer** [comment]
I am wrapping up work on the canvases today (sustainability map) so that on Monday I can get all the updates into T4.

**Comment by johndrevs** [comment]
I can get them into T4 for you. As soon as you have them let me know and I can do it today.

John

On Jul 30, 2017, at 11:05 AM, saradiemer <notifications@github.com<mailto:notifications@github.com>> wrote:


I am wrapping up work on the canvases today (sustainability map) so that on Monday I can get all the updates into T4.

-

**Comment by saradiemer** [comment]
The canvases are all responsive now. All the panels, except the map panel on green canvas, are ready for T4. Steve, let's talk about the styling on the sustainability map tomorrow.

**Comment by johndrevs** [comment]
?Moving these over now. Did the voices on Chicago canvas go from 3 col to 4?



________________________________

**Comment by johndrevs** [comment]
These are all in T4. Give it a look and let me know if I missed anything.

John

On Jul 30, 2017, at 5:59 PM, saradiemer <notifications@github.com<mailto:notifications@github.com>> wrote:


The canvases are all responsive now. All the panels, except the map panel on green canvas, are ready for T4. Steve, let's talk about the styling on the sustainability map tomorrow.

-
