### ISSUE TITLE
TABS/Button Styling

### ISSUE THREAD

**Issue by sravenscraft** [sravenscraft/b3-fw-ug#67]
• Finalize styling on the tabs. Then adjust buttons as needed.

**Comment by sravenscraft** [comment]
We're close. I think we will get there early in the week.

**Comment by johndrevs** [comment]
I just saw this. It looks good.

On Jul 29, 2017, at 5:27 PM, Stephen Ravenscraft <notifications@github.com<mailto:notifications@github.com>> wrote:


We're close. I think we will get there early in the week.

-

**Comment by sravenscraft** [comment]
The look should follow the design of the buttons on the module grid page. Thinner outline and less padding. Can pick up the styling and apply it globally. Thanks.
